# Default values for cm-cluster-issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Example Cluster Issuer Specififcation
clusterIssuer:
  spec:
    acme:
      email: support@acaisoft.com
      solvers: 
      - http01:
          ingress:
            class: nginx
      privateKeySecretRef:
        key: ""
        name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory